# Generated by Django 4.2.2 on 2024-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.URLField(default='Email', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='all_students_enrolled', to='Learn.profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_enrolled_but_completed',
            field=models.ManyToManyField(blank=True, related_name='all_students_completed_course', to='Learn.profile'),
        ),
    ]
